[package]
name = "direct-computing"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
dc-common = { path = "../../crates/dc-common" }
dc-media = { path = "../../crates/dc-media" }
dc-protocol = { path = "../../crates/dc-protocol" }
dc-ui = { path = "../../crates/dc-ui" }

[target.'cfg(windows)'.dependencies]
dc-platform = { path = "../../crates/dc-platform" }

[lints]
workspace = true
