[package]
name = "dc-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Remote desktop orchestration for Direct Computing"

[dependencies]
dc-media = { path = "../dc-media" }
dc-common = { path = "../dc-common" }
dc-protocol = { path = "../dc-protocol" }

[lints]
workspace = true
