[package]
name = "dc-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Authentication and authorization for Direct Computing"

[dependencies]
argon2 = "0.5"
dc-common = { path = "../dc-common" }
dc-protocol = { path = "../dc-protocol" }
rand = "0.8"
sha2 = "0.10"

[lints]
workspace = true
